package agrudados;

import java.awt.BorderLayout;
import java.awt.Dimension;
import java.util.Arrays;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.table.TableRowSorter;
import model.ElementosModel;
import model.elementos;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.statistics.HistogramDataset;
import org.jfree.data.statistics.HistogramType;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Willian
 */
public class Tela_DistribuicaoDeFrequencias extends javax.swing.JInternalFrame {

    ElementosModel modeloTabelaDist = new ElementosModel();
    /**
     * Creates new form AnalisedeGrandesConjntosdeDados
     */
    public Tela_DistribuicaoDeFrequencias() {
        
        initComponents();
        tabelaDistFreq.setModel(modeloTabelaDist);
        tabelaDistFreq.setRowSorter(new TableRowSorter(modeloTabelaDist));
    }
    
    private void carregarIconeAplicacao(JFrame tela, ImageIcon img){
        tela.setIconImage(img.getImage());
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jDialog1 = new javax.swing.JDialog();
        jButton1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        tabelaDistFreq = new javax.swing.JTable();
        panelElementosConjunto = new javax.swing.JPanel();
        botaoAlterarDist = new javax.swing.JButton();
        botaoExcluirDist = new javax.swing.JButton();
        botaoCalcularDist = new javax.swing.JButton();
        caixaDeTextoDist = new javax.swing.JTextField();
        botaoEnviarDist = new javax.swing.JButton();

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setClosable(true);
        setMaximizable(true);
        setOpaque(false);
        setVerifyInputWhenFocusTarget(false);

        jButton1.setText("Exibir Histograma");
        jButton1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                " Classe", "Xi", "fi", "Fi", "fri", "Fri"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable2.setName(""); // NOI18N
        jTable2.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(jTable2);

        tabelaDistFreq.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Elementos Digitados"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tabelaDistFreq);

        panelElementosConjunto.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Elementos do conjunto", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        botaoAlterarDist.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/table_edit.png"))); // NOI18N
        botaoAlterarDist.setText("Alterar");
        botaoAlterarDist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoAlterarDistActionPerformed(evt);
            }
        });

        botaoExcluirDist.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/table_delete.png"))); // NOI18N
        botaoExcluirDist.setText("Excluir");
        botaoExcluirDist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoExcluirDistActionPerformed(evt);
            }
        });

        botaoCalcularDist.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/table.png"))); // NOI18N
        botaoCalcularDist.setText("Tabela");
        botaoCalcularDist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCalcularDistActionPerformed(evt);
            }
        });

        caixaDeTextoDist.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        caixaDeTextoDist.setOpaque(false);
        caixaDeTextoDist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                caixaDeTextoDistActionPerformed(evt);
            }
        });
        caixaDeTextoDist.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                caixaDeTextoDistKeyPressed(evt);
            }
        });

        botaoEnviarDist.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/table_go.png"))); // NOI18N
        botaoEnviarDist.setText("Enviar");
        botaoEnviarDist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoEnviarDistActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelElementosConjuntoLayout = new javax.swing.GroupLayout(panelElementosConjunto);
        panelElementosConjunto.setLayout(panelElementosConjuntoLayout);
        panelElementosConjuntoLayout.setHorizontalGroup(
            panelElementosConjuntoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelElementosConjuntoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelElementosConjuntoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panelElementosConjuntoLayout.createSequentialGroup()
                        .addComponent(botaoCalcularDist)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botaoExcluirDist))
                    .addComponent(caixaDeTextoDist))
                .addGap(18, 18, 18)
                .addGroup(panelElementosConjuntoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(botaoAlterarDist, javax.swing.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE)
                    .addComponent(botaoEnviarDist, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelElementosConjuntoLayout.setVerticalGroup(
            panelElementosConjuntoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelElementosConjuntoLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(panelElementosConjuntoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(caixaDeTextoDist, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoEnviarDist))
                .addGap(18, 18, 18)
                .addGroup(panelElementosConjuntoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoExcluirDist)
                    .addComponent(botaoAlterarDist)
                    .addComponent(botaoCalcularDist))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(panelElementosConjunto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 511, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(97, 97, 97))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(145, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(344, 344, 344))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelElementosConjunto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getAccessibleContext().setAccessibleName("telaDadosAgrupados");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
              
        JFrame frame = new JFrame("Histograma");
        frame.setResizable(false);
        frame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        ImageIcon imageIcon;
        imageIcon = new ImageIcon(getClass().getResource("/imagens/chart_bar.png"));
        carregarIconeAplicacao(frame, imageIcon);

        
        JPanel raiz = new JPanel();
        raiz.setLayout(new BorderLayout());
        Dimension tamanho = new Dimension(600, 450);
        raiz.setPreferredSize(tamanho);
        raiz.setMinimumSize(tamanho);
        frame.add(raiz);
        frame.pack();
        
        frame.setLocation(170, 20);

        // Cria o painel aonde o gráfico será mostrado.
        JPanel primeiroGrafico = new JPanel();
        Dimension tamanhoArea = new Dimension(600, 450);
        primeiroGrafico.setPreferredSize(tamanhoArea);
        primeiroGrafico.setMinimumSize(tamanhoArea);
        raiz.add(primeiroGrafico, BorderLayout.CENTER);

        int tamTabela = tabelaDistFreq.getRowCount();
        double value[] = new double[tamTabela];
        
        for (int i = 0; i < tamTabela; i++) {
            value[i] = Double.parseDouble(tabelaDistFreq.getValueAt(i, 0).toString());
        }

       Arrays.sort(value);
       
       
       int number = tamTabela;
       HistogramDataset dataset = new HistogramDataset();
       dataset.setType(HistogramType.RELATIVE_FREQUENCY);
       dataset.addSeries("Série Aleatória",value, number);

       String plotTitle = ""; 
       String xaxis = "Eixo X";
       String yaxis = "Eixo Y"; 
       PlotOrientation orientation = PlotOrientation.VERTICAL; 
       boolean show = false; 
       boolean toolTips = false;
       boolean urls = false; 
       JFreeChart chart = ChartFactory.createHistogram( plotTitle, xaxis, yaxis, 
                dataset, orientation, show, toolTips, urls);
        ChartPanel chartPanel = new ChartPanel(chart, 600, 450,  600, 450,  600, 450, urls, toolTips, show, urls, show, true);
        primeiroGrafico.add(chartPanel);
        primeiroGrafico.validate();

        frame.setVisible(true);

                
                

    }//GEN-LAST:event_jButton1ActionPerformed

    private void botaoAlterarDistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoAlterarDistActionPerformed

        if (tabelaDistFreq.getSelectedRow() != -1) {

            modeloTabelaDist.setValueAt(caixaDeTextoDist.getText(), tabelaDistFreq.getSelectedRow(), 0);

        }
    }//GEN-LAST:event_botaoAlterarDistActionPerformed

    private void botaoExcluirDistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoExcluirDistActionPerformed

        if (tabelaDistFreq.getSelectedRow() != -1) {

            modeloTabelaDist.removeRow(tabelaDistFreq.getSelectedRow());
        }
    }//GEN-LAST:event_botaoExcluirDistActionPerformed

    private void botaoCalcularDistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCalcularDistActionPerformed

        int tamTabela = tabelaDistFreq.getRowCount();
        double valor[] = new double[tamTabela];
        
        for (int i = 0; i < tamTabela; i++) {
            valor[i] = Double.parseDouble(tabelaDistFreq.getValueAt(i, 0).toString());
        }

        Arrays.sort(valor);
        
        

        
        
    }//GEN-LAST:event_botaoCalcularDistActionPerformed

    private void caixaDeTextoDistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_caixaDeTextoDistActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_caixaDeTextoDistActionPerformed

    private void caixaDeTextoDistKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_caixaDeTextoDistKeyPressed

        if (evt.getKeyCode() == 10) {
            elementos e = new elementos();
            e.setNumeros(Double.parseDouble(caixaDeTextoDist.getText()));
            modeloTabelaDist.addrow(e);
            caixaDeTextoDist.setText("");
        }
    }//GEN-LAST:event_caixaDeTextoDistKeyPressed

    private void botaoEnviarDistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoEnviarDistActionPerformed

        elementos e = new elementos();
        e.setNumeros(Double.parseDouble(caixaDeTextoDist.getText()));
        modeloTabelaDist.addrow(e);
        caixaDeTextoDist.setText("");
    }//GEN-LAST:event_botaoEnviarDistActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoAlterarDist;
    private javax.swing.JButton botaoCalcularDist;
    private javax.swing.JButton botaoEnviarDist;
    private javax.swing.JButton botaoExcluirDist;
    private javax.swing.JTextField caixaDeTextoDist;
    private javax.swing.JButton jButton1;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JPanel panelElementosConjunto;
    private javax.swing.JTable tabelaDistFreq;
    // End of variables declaration//GEN-END:variables
}
